openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MICHELLEALABI/hotelArtichaut/1.0.0
info:
  version: "1.0.0"
  title: "API sécurisée pour l'administration  du site de l'hôtel Artichaut"
  description: >-
    Possibilité de modifier, supprimer ou créer de nouveaux contenus sur la landing page de l'hôtel Artichaut. 
  contact:
    # Un commentaire
    name: Team name 
    email: you@your-company.com
  
security:
  - password:
      - read
      - write
tags: 
  - name: hero
    description: Administration de la section Hero
  - name: promotional_banner
    description: Administration de la bannière promotionnelle
  - name: video_section
    description: Administration de la section Vidéo
  - name: room_categories
    description: Administration de la section Chambres
  - name: advantages
    description: Administration de la section Avantages
  - name: reviews
    description: Administration de la section Avis
  - name: news
    description: Administration de la section Actualités
  - name: footer
    description: Administration du footer
paths:
  /home/hero:
    get:
      tags:
        - hero
      summary: Récupération des éléments du Hero
      description: Affiche le Hero
      responses:
        '200':
          description: Hero affiché
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HeroList'
    
    post:
      tags:
        - hero
      summary: Création d'un nouvel hero
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hero'
      responses:
        '200':
          description: 'Le hero a bien été créé'
        '400':
          description: 'La syntaxe de la requête est erronée.'
  /home/hero/{id}:
    put:
      tags:
        - hero
      summary: Modification d'un hero
      description: Modification d'un hero spécifique
      parameters:
        - in: path
          name: id
          required: true
          description: ID du hero à modifier
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: 'Le hero a bien été créé'
        '400':
          description: 'La syntaxe de la requête est erronée.'
        '404':
          description: 'Ressource non trouvée.'  
            
  /promotional_banner:
    get:
    tags:
      - promotional_banner
      operationId: getPromotionalBanner
      summary: Renvoie les propriétés de la banière promotionnelle.
      description: Cette méthode ne prend aucun paramètre et permet de consulter les champs de la bannière promotionnelle.
      responses:
        '200':
          description: Champs de la bannière promotionnelle.
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/PromotionalBanner'
    put:
      tags:
        - promotional_banner
      operationId: updatePromotionalBanner
      summary: Met à jour la bannière promotionnelle.
      description: Cette méthode permet de modifier la bannière promotionnelle.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromotionalBanner'
      responses:
        '200':
          description: Bannière mise à jour avec succès.
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/PromotionalBanner'

  /home/video_section:
    get:
      tags:
        - video_section
      summary: Récupération des éléments de la section vidéo
      description: >-
        Liste des sections vidéo
      responses:
        '200':
          description: Section vidéo affichées
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoSectionList'  
  
    post:
        tags:
          - video_section
        summary: Création d'une nouvelle section Vidéo
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoSection'
        responses:
          '200':
            description: 'La section vidéo a bien été créé'
          '400':
            description: 'La syntaxe de la requête est erronée.'
  /home/video_section/{id}:
    put:
      tags:
        - video_section
      summary: Modification d'une section vidéo
      description: Modification d'une section vidéo spécifique
      parameters:
        - in: path
          name: id
          required: true
          description: ID de la section vidéo à modifier
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: 'Le hero a bien été créé'
        '400':
          description: 'La syntaxe de la requête est erronée.'
        '404':
          description: 'Ressource non trouvée.' 
  
  /home/rooms:
    get:
      tags:
        - rooms
      summary: Récupération des éléments de la section Room Categories
      description: >-
        Liste des éléments de la section Room Categories
      responses:
        '200':
          description: Elements de la section Room Categories affichés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomCategories'
  /home/rooms/{id}:  
    put:
      tags:
        - rooms
      summary: Modification d'une nouvelle section Rooms
      parameters:
        - in: path
          name: id
          required: true
          description: ID de la catégorie à modifier
          schema:
            type: integer
            example: 10
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomsList'
      responses:
        '200':
          description: 'La catégorie a bien été modifiée'
        '400':
          description: 'La syntaxe de la requête est erronée.'
        '404':
          description: 'Ressource non trouvée.' 

  /home/advantages:
    get:
      tags: 
        - advantages
      operationId: getAllAdvantages
      summary: Récupère les avantages.
      description: Cette section retourne tous les avantages mis en avant par l'hôtel.
      responses:
        '200':
          description: Renvoie tous les avantages.
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Advantages'
  /home/advantages/{id}:
    put:
      tags:
        - advantages
      operationId: updateAdvantage
      summary: Modifie l'un des avantages.
      description: >-
        Cette méthode prend un paramètre (numéro) et met à jour le rang qui correspond à cet ID. Attention, le rang doit contenir tous les champs : aucun ne peut être supprimé sans remplacement.
      parameters:
        - in: path
          name: id
          required: true
          description: Id de l'avantage à modifier
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Advantages'
      responses:
        '200':
          description: 'Avantage mis à jour.'
        '400':
          description: 'La syntaxe de la requête est erronée.'
        '404':
          description: 'Ressource non trouvée.'  
  
components:
  schemas: 
    Hero:
      description: Modèle contenant les éléments du hero
      type: object
      required:
        - id
        - title
        - subtitle
        - media_id
        - title_english
        - subtitle_english
       
      properties:
        id:
          type: integer
          example: 5
        title:
          type: string
          example: Titre de page
        subtitle:
          type: string
          example: Le sous titre de ma page
        media_url:
          type: string
          example: path/to/the/file
        title_english:
          type: string
          example: The Title
        subtitle_english:
          type: string
          example: The subtitle of may page
        
    PromotionalBanner:
      description: Modèle contenant les éléments de la bannière promotionnelle.
      type: object
      required:
        - id
        - text_french
        - text_english

      properties:
        id:
          type: integer
          example: 0
        text_french:
          type: string
          example: "Mon texte français"
        text_english:
          type: string
          example: "My english text"

    VideoSection:
      description: Modèle contenant les éléments de la section Vidéo
      type: object
      required:
        - id
        - video_url
        - title
        - title_english
        - description
        - description_english
       
      properties:
        id:
          type: integer
          example: 4
        video_url:
          type: string
          format: url
          example: 'https://www.hotelArtichaud.com/video1'
        title:
          type: string
          example: Titre de ma vidéo
        title_english:
          type: string
          example: The title in english
        description:
          type: string
          example: La description de la vidéo
        description_english:
          type: string
          example: The description in english
        
    Advantages:
      description: Modèle contenant les éléments de la section Avantages 
      type: object
      required:
        - icon_url
        - title_french
        - title_english
        - description_french
        - description_english

      properties:
        id:
          type: integer
          example: 3
        icon_url:
          type: string
          example: 'https://fonts.googleapis.com/icon?family=Material+Icons'
        title_french: 
          type: string
          example: "Mon titre en français"
        title_english:
          type: string
          example: "My english title"
        description_french:
          type: string
          example: "Description de mon avantage"
        description_english:
          type: string
          example: "Description of my advantage"
      
      Reviews:
      description: Modèle contenant les éléments d'un avis.
      type: object
      required:
          - id
          - customer_id
          - rating
          - body
          - is_displayed
          - created_at

      properties:
        id:
          type: integer
          format: int64
          example: 12
        customer_id:
          type: integer
          format: int64
          example: 14
        rating:
          type: number
          format: float
          example: 3.5
        body:
          type: string
          example: "Voilà mon avis"
        is_displayed:
          type: boolean
          example: false
        created_at:
          type: string
          format: timestamp

  securitySchemes:
    password:
      type: oauth2
      flows:
        password:
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources